/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cloudproject.view;

import br.com.cloudproject.constantes.constantes;
import javax.swing.JOptionPane;

/**
 *
 * @author Debug
 */
public class dProjeto extends javax.swing.JDialog {

    telaPrincipal principal;
    dNProjeto novoProjeto;
    dAProjeto analiseProjeto;
    
    /**
     * Creates new form dProjeto
     */
    public dProjeto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        preencheTextos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGroup = new javax.swing.ButtonGroup();
        labelOperacao = new javax.swing.JLabel();
        btEntrar = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        btCancelar = new javax.swing.JButton();
        panelRadios = new javax.swing.JPanel();
        radioNovo = new javax.swing.JRadioButton();
        radioOpcoes = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelOperacao.setText("jLabel1");

        btEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudproject/images/sim.png"))); // NOI18N
        btEntrar.setText("jButton1");
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Título");

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudproject/images/cancelar.png"))); // NOI18N
        btCancelar.setText("jButton2");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        panelRadios.setBackground(new java.awt.Color(255, 255, 255));
        panelRadios.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btGroup.add(radioNovo);
        radioNovo.setText("Novo Projeto");

        btGroup.add(radioOpcoes);
        radioOpcoes.setText("Outras Opções");

        javax.swing.GroupLayout panelRadiosLayout = new javax.swing.GroupLayout(panelRadios);
        panelRadios.setLayout(panelRadiosLayout);
        panelRadiosLayout.setHorizontalGroup(
            panelRadiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadiosLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(radioNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(radioOpcoes)
                .addGap(47, 47, 47))
        );
        panelRadiosLayout.setVerticalGroup(
            panelRadiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadiosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRadiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioNovo)
                    .addComponent(radioOpcoes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelOperacao)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btEntrar)
                        .addGap(55, 55, 55)
                        .addComponent(btCancelar))
                    .addComponent(panelRadios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelOperacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRadios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEntrar)
                    .addComponent(btCancelar))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed
        if(radioNovo.isSelected()){
            principal = new telaPrincipal();
            novoProjeto = new dNProjeto(principal, true);
            novoProjeto.setTitle("NOVO PROJETO");
            novoProjeto.setLocationRelativeTo(novoProjeto);
            novoProjeto.setVisible(true);
        }else if(radioOpcoes.isSelected()){
            principal = new telaPrincipal();
            analiseProjeto = new dAProjeto(principal, true);
            analiseProjeto.setTitle("ANÁLISE DE PROJETOS");
            analiseProjeto.setLocationRelativeTo(analiseProjeto);
            analiseProjeto.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, selecione a opção.");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btEntrarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        sair();
        // TODO add your handling code here:
    }//GEN-LAST:event_btCancelarActionPerformed

    public void sair(){
        dispose();
    }
    
    public void preencheTextos(){
        labelTitulo.setText(constantes.PTITULOPROJETO);
        labelOperacao.setText(constantes.SELECOPERACAO);
        btEntrar.setText(constantes.BTENTRAR);
        btCancelar.setText(constantes.BTCANCELAR);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dProjeto dialog = new dProjeto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btEntrar;
    private javax.swing.ButtonGroup btGroup;
    private javax.swing.JLabel labelOperacao;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelRadios;
    private javax.swing.JRadioButton radioNovo;
    private javax.swing.JRadioButton radioOpcoes;
    // End of variables declaration//GEN-END:variables
}
