/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cloudproject.view;

/**
 *
 * @author Debug
 */
public class Produtividade extends javax.swing.JDialog {

    /**
     * Creates new form Produtividade
     */
    public Produtividade(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFundo = new javax.swing.JPanel();
        labelData = new javax.swing.JLabel();
        txtData = new javax.swing.JFormattedTextField();
        labelHoraInicio = new javax.swing.JLabel();
        txtHoraInicio = new javax.swing.JFormattedTextField();
        labelHoraFinal = new javax.swing.JLabel();
        txtHoraFinal = new javax.swing.JFormattedTextField();
        btInicio = new javax.swing.JButton();
        btFinal = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        labelExpediente = new javax.swing.JLabel();
        checkDataHoje = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        labelAlimentacao = new javax.swing.JLabel();
        labelPausa = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        labelHoraInicioA = new javax.swing.JLabel();
        txtHoraInicioA = new javax.swing.JFormattedTextField();
        btInicioA = new javax.swing.JButton();
        labelHoraFinalA = new javax.swing.JLabel();
        txtHoraFinalA = new javax.swing.JFormattedTextField();
        btFinalA = new javax.swing.JButton();
        labelHoraTotalExpediente = new javax.swing.JLabel();
        labelHoraTotalAlimentacao = new javax.swing.JLabel();
        labelHoraInicioP = new javax.swing.JLabel();
        txtHoraInicioP = new javax.swing.JFormattedTextField();
        btInicioP = new javax.swing.JButton();
        labelHoraFinalP = new javax.swing.JLabel();
        txtHoraFinalP = new javax.swing.JFormattedTextField();
        btFinalP = new javax.swing.JButton();
        labelHoraTotalPausa = new javax.swing.JLabel();
        labelDescricaoPausa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelFundo.setBackground(new java.awt.Color(255, 255, 255));
        panelFundo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        labelData.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelData.setText("Data: ");

        txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });

        labelHoraInicio.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelHoraInicio.setText("Hora Início:");

        txtHoraInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        labelHoraFinal.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelHoraFinal.setText("Hora Final: ");

        txtHoraFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        btInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudproject/images/sim.png"))); // NOI18N
        btInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInicioActionPerformed(evt);
            }
        });

        btFinal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudproject/images/sim.png"))); // NOI18N
        btFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinalActionPerformed(evt);
            }
        });

        labelExpediente.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelExpediente.setText("Expediente");

        checkDataHoje.setBackground(new java.awt.Color(255, 255, 255));
        checkDataHoje.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        checkDataHoje.setText("Hoje");

        labelAlimentacao.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelAlimentacao.setText("Alimentação");

        labelPausa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelPausa.setText("Pausas");

        labelHoraInicioA.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelHoraInicioA.setText("Hora Início:");

        txtHoraInicioA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        btInicioA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudproject/images/sim.png"))); // NOI18N
        btInicioA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInicioAActionPerformed(evt);
            }
        });

        labelHoraFinalA.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelHoraFinalA.setText("Hora Final: ");

        txtHoraFinalA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        btFinalA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudproject/images/sim.png"))); // NOI18N
        btFinalA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinalAActionPerformed(evt);
            }
        });

        labelHoraTotalExpediente.setText("Hora Total");

        labelHoraTotalAlimentacao.setText("Hora Total");

        labelHoraInicioP.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelHoraInicioP.setText("Hora Início:");

        txtHoraInicioP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        btInicioP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudproject/images/sim.png"))); // NOI18N
        btInicioP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInicioPActionPerformed(evt);
            }
        });

        labelHoraFinalP.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelHoraFinalP.setText("Hora Final: ");

        txtHoraFinalP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        btFinalP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cloudproject/images/sim.png"))); // NOI18N
        btFinalP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinalPActionPerformed(evt);
            }
        });

        labelHoraTotalPausa.setText("Hora Total");

        labelDescricaoPausa.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelDescricaoPausa.setText("Descrição:");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout panelFundoLayout = new javax.swing.GroupLayout(panelFundo);
        panelFundo.setLayout(panelFundoLayout);
        panelFundoLayout.setHorizontalGroup(
            panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFundoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkDataHoje)
                .addGap(199, 199, 199))
            .addGroup(panelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3)
                    .addComponent(labelExpediente)
                    .addComponent(labelAlimentacao)
                    .addGroup(panelFundoLayout.createSequentialGroup()
                        .addComponent(labelHoraInicioA)
                        .addGap(18, 18, 18)
                        .addComponent(txtHoraInicioA, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btInicioA, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(labelHoraFinalA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHoraFinalA, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btFinalA, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelHoraTotalAlimentacao))
                    .addGroup(panelFundoLayout.createSequentialGroup()
                        .addComponent(labelHoraInicio)
                        .addGap(18, 18, 18)
                        .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(labelHoraFinal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelHoraTotalExpediente))
                    .addComponent(labelPausa)
                    .addGroup(panelFundoLayout.createSequentialGroup()
                        .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelHoraInicioP)
                            .addComponent(labelDescricaoPausa))
                        .addGap(18, 18, 18)
                        .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFundoLayout.createSequentialGroup()
                                .addComponent(txtHoraInicioP, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btInicioP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(labelHoraFinalP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHoraFinalP, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btFinalP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelHoraTotalPausa))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelFundoLayout.setVerticalGroup(
            panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFundoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelData)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkDataHoje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelExpediente)
                .addGap(18, 18, 18)
                .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHoraInicio)
                            .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHoraFinal)
                            .addComponent(txtHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelHoraTotalExpediente))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAlimentacao)
                .addGap(18, 18, 18)
                .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHoraInicioA)
                            .addComponent(txtHoraInicioA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHoraFinalA)
                            .addComponent(txtHoraFinalA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btInicioA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btFinalA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelHoraTotalAlimentacao))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPausa)
                .addGap(18, 18, 18)
                .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHoraInicioP)
                            .addComponent(txtHoraInicioP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHoraFinalP)
                            .addComponent(txtHoraFinalP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btInicioP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btFinalP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelHoraTotalPausa))
                .addGap(18, 18, 18)
                .addGroup(panelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDescricaoPausa)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btInicioActionPerformed

    private void btFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btFinalActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void btInicioAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInicioAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btInicioAActionPerformed

    private void btFinalAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinalAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btFinalAActionPerformed

    private void btInicioPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInicioPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btInicioPActionPerformed

    private void btFinalPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinalPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btFinalPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produtividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Produtividade dialog = new Produtividade(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFinal;
    private javax.swing.JButton btFinalA;
    private javax.swing.JButton btFinalP;
    private javax.swing.JButton btInicio;
    private javax.swing.JButton btInicioA;
    private javax.swing.JButton btInicioP;
    private javax.swing.JCheckBox checkDataHoje;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelAlimentacao;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelDescricaoPausa;
    private javax.swing.JLabel labelExpediente;
    private javax.swing.JLabel labelHoraFinal;
    private javax.swing.JLabel labelHoraFinalA;
    private javax.swing.JLabel labelHoraFinalP;
    private javax.swing.JLabel labelHoraInicio;
    private javax.swing.JLabel labelHoraInicioA;
    private javax.swing.JLabel labelHoraInicioP;
    private javax.swing.JLabel labelHoraTotalAlimentacao;
    private javax.swing.JLabel labelHoraTotalExpediente;
    private javax.swing.JLabel labelHoraTotalPausa;
    private javax.swing.JLabel labelPausa;
    private javax.swing.JPanel panelFundo;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JFormattedTextField txtHoraFinal;
    private javax.swing.JFormattedTextField txtHoraFinalA;
    private javax.swing.JFormattedTextField txtHoraFinalP;
    private javax.swing.JFormattedTextField txtHoraInicio;
    private javax.swing.JFormattedTextField txtHoraInicioA;
    private javax.swing.JFormattedTextField txtHoraInicioP;
    // End of variables declaration//GEN-END:variables
}
